### ISSUE TITLE
Wrong cmd folder

### ISSUE THREAD

**Issue by metalmatze** [StackPointCloud/digitalocean-flex-volume#4]
This project is called `digitalocean-flex-volumes` but the folder in `cmd/` is called `digitalocean-flex-volume`. There's an `s` missing at the end.

**Comment by odacremolbap** [comment]
thanks a lot @metalmatze 
I commented this issue to the repo owner, since the singluar `digitalocean-flex-volume` plugin sounded better than the existing `digitalocean-flex-volumes`

He has already changed the name to what I guess is a better naming.
